DROP TABLE IF EXISTS `tblProducts`;
CREATE TABLE `tblProducts` (
  `intProductID` int(11) NOT NULL AUTO_INCREMENT,
  `strName` varchar(100) DEFAULT '',
  `curDefaultAmount` decimal(12,2) DEFAULT '0.00',
  `intMinChangeLevel` int(11) DEFAULT '0',
  `intMinSellLevel` int(11) DEFAULT '0',
  `intCreatedLevel` int(11) DEFAULT '0',
  `intCreatedID` int(11) DEFAULT '0',
  `intEntityID` int(11) DEFAULT '0',
  `intRealmID` int(11) DEFAULT '0',
  `intAssocUnique` int(11) DEFAULT '0',
  `strGSTText` varchar(200) DEFAULT '',
  `intAllowMultiPurchase` int(11) DEFAULT '0',
  `intMandatoryProductID` int(11) DEFAULT '0',
  `strGroup` varchar(100) DEFAULT '',
  `strProductNotes` text,
  `intInactive` int(11) DEFAULT '0',
  `intAllowQtys` tinyint(4) DEFAULT '0',
  `intProductGender` tinyint(4) DEFAULT '0',
  `intSetMemberActive` tinyint(4) DEFAULT '0',
  `intSetMemberFinancial` tinyint(4) DEFAULT '0',
  `intProductExpiryDays` smallint(6) DEFAULT '0',
  `intMemberExpiryDays` smallint(6) DEFAULT '0',
  `dtProductExpiry` datetime DEFAULT NULL,
  `dtMemberExpiry` datetime DEFAULT NULL,
  `intProductMemberPackageID` int(11) DEFAULT '0',
  `intPaymentSplitID` int(11) NOT NULL DEFAULT '0',
  `intProductType` int(11) DEFAULT '0',
  `intIsEvent` tinyint(4) DEFAULT NULL,
  `intProductSubRealmID` int(11) DEFAULT '0',
  `intSeasonPlayerFinancial` tinyint(4) DEFAULT '0',
  `intSeasonCoachFinancial` tinyint(4) DEFAULT '0',
  `intSeasonUmpireFinancial` tinyint(4) DEFAULT '0',
  `intSeasonOther1Financial` tinyint(4) DEFAULT '0',
  `intSeasonOther2Financial` tinyint(4) DEFAULT '0',
  `intSeasonMemberPackageID` int(11) DEFAULT '0',
  `intProductSeasonID` int(11) DEFAULT '0',
  `dtDateAvailableFrom` datetime DEFAULT NULL,
  `dtDateAvailableTo` datetime DEFAULT NULL,
  `strLMSCourseID` varchar(20) DEFAULT '0',
  `intMatchCreditsPerQty` int(11) DEFAULT '0',
  `intMatchCreditType` int(11) DEFAULT '0',
  `intPhoto` tinyint(4) DEFAULT '0',
    intCanResetPaymentRequired TINYINT DEFAULT 0,
  PRIMARY KEY (`intProductID`),
  KEY `index_intEntityID` (`intEntityID`),
  KEY `index_intRealmID` (`intRealmID`),
  KEY `index_intInactive` (`intInactive`),
  KEY `index_intProductType` (`intProductType`),
  KEY `index_productSeasonID` (`intProductSeasonID`)
) DEFAULT CHARSET=utf8;

