DROP TABLE IF EXISTS tblUserHash;
CREATE TABLE tblUserHash (
    userId INT UNSIGNED NOT NULL,
    passwordHash VARCHAR(100),
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (userId)
);

