ALTER TABLE tblAssoc ADD COLUMN intDataAccess	INT NOT NULL DEFAULT 2;
ALTER TABLE tblRegion ADD COLUMN intDataAccess	INT NOT NULL DEFAULT 2;
ALTER TABLE tblZone ADD COLUMN intDataAccess	INT NOT NULL DEFAULT 2;
