DROP TABLE IF EXISTS `tblTransactions`;
CREATE TABLE `tblTransactions` (
  `intTransactionID` int(11) NOT NULL auto_increment,
  `intStatus` tinyint(4) default '0',
  `strNotes` text,
  `curAmount` decimal(12,2) default NULL,
  `intQty` int(11) default '0',
  `dtTransaction` datetime default NULL,
  `dtPaid` datetime default NULL,
  `tTimeStamp` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `intDelivered` tinyint(11) default '0',
  `intAssocID` int(11) default '0',
  `intRealmID` int(11) default '0',
  `intRealmSubTypeID` int(11) default '0',
  `intID` int(11) default '0',
  `intTableType` tinyint(4) default '0',
  `intPaymentType` int(11) default '0',
  `strReceiptRef` varchar(100) default NULL,
  `intProductID` int(11) default NULL,
  `intTransLogID` int(11) default '0',
  `intCurrencyID` int(11) default '0',
  `intTempLogID` int(11) default '0',
  PRIMARY KEY  (`intTransactionID`),
  KEY `index_intStatus` (`intStatus`),
  KEY `index_intAssocID` (`intAssocID`),
  KEY `transLogID` (`intTransLogID`),
  KEY index_intRealmIDintRealmSubTypeID (intRealmID, intRealmSubTypeID),
  KEY `intRealmSubTypeID` (`intRealmSubTypeID`),
  KEY index_intIDintTableType (intID, intTableType),
  KEY `intTableType` (`intTableType`),
  KEY `intProductID` (`intProductID`)
);
